name: AnthoPlugManager
version: '${project.version}'
main: com.antho.anthoplugmanager.AnthoPlugManager
api-version: '1.20'
commands:
  disable:
    description: disable plugin
    permission: anthoplugin.disable
  enable:
    description: enable plugin
    permission: anthoplugin.enable
  rs:
    description: reload server
    permission: anthoplugin.reloadserver
permissions:
  anthoplugin.reloadserver:
    default: false
  anthoplugin.disable:
    default: false
  anthoplugin.enable:
    default: true