name: AnthoPlugManager
version: '${project.version}'
main: com.antho.anthoplugmanager.AnthoPlugManager
api-version: '1.20'
commands:
  disable:
    description: disable plugin
  enable:
    description: enable plugin
  rs:
    description: reload server